// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EduDirectory3.Models;

public partial class ActividadExtracurricularPreferencia
{
    [Key]
    public int IdActividadExtracurricularPreferencia { get; set; }

    [Required]
    [StringLength(150)]
    public string NombreActividadExtracurricularPreferencia { get; set; }

    public int IdFormularioPreferencia { get; set; }

    [ForeignKey("IdFormularioPreferencia")]
    [InverseProperty("ActividadExtracurricularPreferencia")]
    public virtual FormularioPreferencia IdFormularioPreferenciaNavigation { get; set; }
}