// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EduDirectory3.Models;
//648546586546
public partial class Calificacion
{
    [Key]
    public int IdCalificacion { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal CalificacionAmbienteEscolar { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal CalificacionMetodologia { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal CalificacionSeguridad { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal CalificacionProfesores { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal CalificacionActividadesExtracurriculares { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal CalificacionInfraestructura { get; set; }

    public int IdEvaluacion { get; set; }

    [ForeignKey("IdEvaluacion")]
    [InverseProperty("Calificacion")]
    public virtual Evaluacion IdEvaluacionNavigation { get; set; }
}