// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EduDirectory3.Models;

public partial class Chatbot
{
    [Key]
    public int IdChatbot { get; set; }

    public DateOnly Fecha { get; set; }

    [Required]
    [StringLength(1000)]
    public string Mensaje { get; set; }

    public int IdUsuario { get; set; }

    [InverseProperty("IdChatbotNavigation")]
    public virtual ICollection<Filtro> Filtro { get; set; } = new List<Filtro>();

    [ForeignKey("IdUsuario")]
    [InverseProperty("Chatbot")]
    public virtual Usuario IdUsuarioNavigation { get; set; }
}