// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EduDirectory3.Models;

public partial class Coordenada
{
    [Key]
    public int IdCoordenada { get; set; }

    [Column(TypeName = "decimal(18, 10)")]
    public decimal CoordenadaX { get; set; }

    [Column(TypeName = "decimal(18, 10)")]
    public decimal CoordenadaY { get; set; }

    public int IdUbicacion { get; set; }

    [ForeignKey("IdUbicacion")]
    [InverseProperty("Coordenada")]
    public virtual Ubicacion IdUbicacionNavigation { get; set; }
}