// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EduDirectory3.Models;

public partial class Email
{
    [Key]
    public int IdEmail { get; set; }

    [Required]
    [Column("Email")]
    [StringLength(150)]
    public string Email1 { get; set; }

    public int IdInstitucion { get; set; }

    [Required]
    [StringLength(150)]
    public string PerteneceA { get; set; }

    [ForeignKey("IdInstitucion")]
    [InverseProperty("Email")]
    public virtual Institucion IdInstitucionNavigation { get; set; }
}