// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EduDirectory3.Models;

public partial class Evaluacion
{
    [Key]
    public int IdEvaluacion { get; set; }

    [Required]
    [StringLength(500)]
    public string Comentario { get; set; }

    public int IdUsuario { get; set; }

    public int IdSede { get; set; }

    public bool? Reportado { get; set; }

    [StringLength(1000)]
    public string MotivoReporte { get; set; }

    [InverseProperty("IdEvaluacionNavigation")]
    public virtual ICollection<Calificacion> Calificacion { get; set; } = new List<Calificacion>();

    [ForeignKey("IdSede")]
    [InverseProperty("Evaluacion")]
    public virtual Sede IdSedeNavigation { get; set; }

    [ForeignKey("IdUsuario")]
    [InverseProperty("Evaluacion")]
    public virtual Usuario IdUsuarioNavigation { get; set; }
}