// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EduDirectory3.Models;

public partial class Filtro
{
    [Key]
    public int IdFiltro { get; set; }

    [Required]
    [StringLength(100)]
    public string NombreFiltro { get; set; }

    public int IdChatbot { get; set; }

    [ForeignKey("IdChatbot")]
    [InverseProperty("Filtro")]
    public virtual Chatbot IdChatbotNavigation { get; set; }
}