// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EduDirectory3.Models;

public partial class FormularioContacto
{
    [Key]
    public int IdFormularioContacto { get; set; }

    [Required]
    [StringLength(100)]
    public string Nombre { get; set; }

    [Required]
    [StringLength(1000)]
    public string Mensaje { get; set; }

    public int IdUsuario { get; set; }

    public int IdSede { get; set; }

    [ForeignKey("IdSede")]
    [InverseProperty("FormularioContacto")]
    public virtual Sede IdSedeNavigation { get; set; }

    [ForeignKey("IdUsuario")]
    [InverseProperty("FormularioContacto")]
    public virtual Usuario IdUsuarioNavigation { get; set; }
}