// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EduDirectory3.Models;

public partial class FormularioPreferencia
{
    [Key]
    public int IdFormularioPreferencia { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Presupuesto { get; set; }

    public int EdadEstudiante { get; set; }

    [Required]
    [StringLength(100)]
    public string TipoPreferencia { get; set; }

    [Required]
    [StringLength(100)]
    public string MetodologiaPreferencia { get; set; }

    public int IdUsuario { get; set; }

    [InverseProperty("IdFormularioPreferenciaNavigation")]
    public virtual ICollection<ActividadExtracurricularPreferencia> ActividadExtracurricularPreferencia { get; set; } = new List<ActividadExtracurricularPreferencia>();

    [ForeignKey("IdUsuario")]
    [InverseProperty("FormularioPreferencia")]
    public virtual Usuario IdUsuarioNavigation { get; set; }

    [InverseProperty("IdFormularioPreferenciaNavigation")]
    public virtual ICollection<JornadaPreferencia> JornadaPreferencia { get; set; } = new List<JornadaPreferencia>();

    [InverseProperty("IdFormularioPreferenciaNavigation")]
    public virtual ICollection<NivelPreferencia> NivelPreferencia { get; set; } = new List<NivelPreferencia>();

    [InverseProperty("IdFormularioPreferenciaNavigation")]
    public virtual ICollection<ServiciosPreferencia> ServiciosPreferencia { get; set; } = new List<ServiciosPreferencia>();
}