// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EduDirectory3.Models;

public partial class Institucion
{
    [Key]
    public int IdInstitucion { get; set; }

    [Required]
    [StringLength(150)]
    public string Nombre { get; set; }

    [Required]
    [StringLength(255)]
    public string PaginaWeb { get; set; }

    [Required]
    [StringLength(255)]
    public string Imagen { get; set; }

    [Required]
    [StringLength(100)]
    public string Metodologia { get; set; }

    [Required]
    [StringLength(50)]
    public string Calendario { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Costo { get; set; }

    [Required]
    [StringLength(50)]
    public string Tipo { get; set; }

    [Required]
    [StringLength(1000)]
    public string Descripcion { get; set; }

    [Required]
    [StringLength(80)]
    public string HorarioAtencion { get; set; }

    public int? IdUsuario { get; set; }

    [InverseProperty("IdInstitucionNavigation")]
    public virtual ICollection<Email> Email { get; set; } = new List<Email>();

    [ForeignKey("IdUsuario")]
    [InverseProperty("Institucion")]
    public virtual Usuario IdUsuarioNavigation { get; set; }

    [InverseProperty("IdInstitucionNavigation")]
    public virtual ICollection<Rector> Rector { get; set; } = new List<Rector>();

    [InverseProperty("IdInstitucionNavigation")]
    public virtual ICollection<ResultadosIcfes> ResultadosIcfes { get; set; } = new List<ResultadosIcfes>();

    [InverseProperty("IdInstitucionNavigation")]
    public virtual ICollection<Sede> Sede { get; set; } = new List<Sede>();
}