// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EduDirectory3.Models;

public partial class Jornada
{
    [Key]
    public int IdJornada { get; set; }

    [Required]
    [StringLength(100)]
    public string NombreJornada { get; set; }

    public int IdSede { get; set; }

    [ForeignKey("IdSede")]
    [InverseProperty("Jornada")]
    public virtual Sede IdSedeNavigation { get; set; }
}