// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EduDirectory3.Models;

public partial class JornadaPreferencia
{
    [Key]
    public int IdJornadaPreferencia { get; set; }

    [Required]
    [StringLength(100)]
    public string NombreJornadaPreferencia { get; set; }

    public int IdFormularioPreferencia { get; set; }

    [ForeignKey("IdFormularioPreferencia")]
    [InverseProperty("JornadaPreferencia")]
    public virtual FormularioPreferencia IdFormularioPreferenciaNavigation { get; set; }
}