// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EduDirectory3.Models;

public partial class Rector
{
    [Key]
    public int IdRector { get; set; }

    [Required]
    [StringLength(100)]
    public string Nombre { get; set; }

    [Required]
    [StringLength(100)]
    public string Apellido { get; set; }

    [Required]
    [StringLength(20)]
    public string Telefono { get; set; }

    [Required]
    [StringLength(150)]
    public string Email { get; set; }

    public int IdInstitucion { get; set; }

    [ForeignKey("IdInstitucion")]
    [InverseProperty("Rector")]
    public virtual Institucion IdInstitucionNavigation { get; set; }
}