// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EduDirectory3.Models;

public partial class ResultadosIcfes
{
    [Key]
    public int Id { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal Puntaje { get; set; }

    public int Anio { get; set; }

    public int IdInstitucion { get; set; }

    [ForeignKey("IdInstitucion")]
    [InverseProperty("ResultadosIcfes")]
    public virtual Institucion IdInstitucionNavigation { get; set; }
}