// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EduDirectory3.Models;

public partial class Sede
{
    [Key]
    public int IdSede { get; set; }

    [Required]
    [StringLength(150)]
    public string NombreSede { get; set; }

    public int IdInstitucion { get; set; }

    [InverseProperty("IdSedeNavigation")]
    public virtual ICollection<ActividadesExtracurriculares> ActividadesExtracurriculares { get; set; } = new List<ActividadesExtracurriculares>();

    [InverseProperty("IdSedeNavigation")]
    public virtual ICollection<Evaluacion> Evaluacion { get; set; } = new List<Evaluacion>();

    [InverseProperty("IdSedeNavigation")]
    public virtual ICollection<FormularioContacto> FormularioContacto { get; set; } = new List<FormularioContacto>();

    [ForeignKey("IdInstitucion")]
    [InverseProperty("Sede")]
    public virtual Institucion IdInstitucionNavigation { get; set; }

    [InverseProperty("IdSedeNavigation")]
    public virtual ICollection<Jornada> Jornada { get; set; } = new List<Jornada>();

    [InverseProperty("IdSedeNavigation")]
    public virtual ICollection<Nivel> Nivel { get; set; } = new List<Nivel>();

    [InverseProperty("IdSedeNavigation")]
    public virtual ICollection<Servicio> Servicio { get; set; } = new List<Servicio>();

    [InverseProperty("IdSedeNavigation")]
    public virtual ICollection<Telefono> Telefono { get; set; } = new List<Telefono>();

    [InverseProperty("IdSedeNavigation")]
    public virtual ICollection<Ubicacion> Ubicacion { get; set; } = new List<Ubicacion>();
}