// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EduDirectory3.Models;

public partial class Servicio
{
    [Key]
    public int IdServicio { get; set; }

    [Required]
    [StringLength(150)]
    public string NombreServicio { get; set; }

    public int IdSede { get; set; }

    [ForeignKey("IdSede")]
    [InverseProperty("Servicio")]
    public virtual Sede IdSedeNavigation { get; set; }
}