// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EduDirectory3.Models;

public partial class Telefono
{
    [Key]
    public int IdTelefono { get; set; }

    [Required]
    [StringLength(20)]
    public string NumeroTelefono { get; set; }

    public int IdSede { get; set; }

    [ForeignKey("IdSede")]
    [InverseProperty("Telefono")]
    public virtual Sede IdSedeNavigation { get; set; }
}