// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EduDirectory3.Models;

public partial class Ubicacion
{
    [Key]
    public int IdUbicacion { get; set; }

    [Required]
    [StringLength(200)]
    public string Direccion { get; set; }

    [Required]
    [StringLength(100)]
    public required string Barrio { get; set; }

    [Required]
    [StringLength(100)]
    public string Comuna { get; set; }

    public int IdSede { get; set; }

    [InverseProperty("IdUbicacionNavigation")]
    public virtual ICollection<Coordenada> Coordenada { get; set; } = new List<Coordenada>();

    [ForeignKey("IdSede")]
    [InverseProperty("Ubicacion")]
    public virtual Sede IdSedeNavigation { get; set; }
}