// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EduDirectory3.Models;

[Index("Correo", Name = "UQ__Usuario__60695A1997325780", IsUnique = true)]
public partial class Usuario
{
    [Key]
    public int IdUsuario { get; set; }

    [Required]
    [StringLength(100)]
    public string Nombre { get; set; }

    [Required]
    [StringLength(100)]
    public string Apellido { get; set; }

    [Required]
    [StringLength(50)]
    public string Rol { get; set; }

    [Required]
    [StringLength(150)]
    public string Correo { get; set; }

    [Required]
    [StringLength(255)]
    public string Contrasena { get; set; }

    [InverseProperty("IdUsuarioNavigation")]
    public virtual ICollection<Chatbot> Chatbot { get; set; } = new List<Chatbot>();

    [InverseProperty("IdUsuarioNavigation")]
    public virtual ICollection<Evaluacion> Evaluacion { get; set; } = new List<Evaluacion>();

    [InverseProperty("IdUsuarioNavigation")]
    public virtual ICollection<FormularioContacto> FormularioContacto { get; set; } = new List<FormularioContacto>();

    [InverseProperty("IdUsuarioNavigation")]
    public virtual ICollection<FormularioPreferencia> FormularioPreferencia { get; set; } = new List<FormularioPreferencia>();

    [InverseProperty("IdUsuarioNavigation")]
    public virtual ICollection<Institucion> Institucion { get; set; } = new List<Institucion>();
}