// <auto-generated />
using System;
using EduDirectory3.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EduDirectory3.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EduDirectory3.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("EduDirectory3.Models.ActividadExtracurricularPreferencia", b =>
                {
                    b.Property<int>("IdActividadExtracurricularPreferencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdActividadExtracurricularPreferencia"));

                    b.Property<int>("IdFormularioPreferencia")
                        .HasColumnType("int");

                    b.Property<string>("NombreActividadExtracurricularPreferencia")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdActividadExtracurricularPreferencia")
                        .HasName("PK__Activida__1FD12A63972B702B");

                    b.HasIndex("IdFormularioPreferencia");

                    b.ToTable("ActividadExtracurricularPreferencia");
                });

            modelBuilder.Entity("EduDirectory3.Models.ActividadesExtracurriculares", b =>
                {
                    b.Property<int>("IdActividadesExtracurriculares")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdActividadesExtracurriculares"));

                    b.Property<int>("IdSede")
                        .HasColumnType("int");

                    b.Property<string>("NombreActividad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdActividadesExtracurriculares")
                        .HasName("PK__Activida__4D054355988EB3F5");

                    b.HasIndex("IdSede");

                    b.ToTable("ActividadesExtracurriculares");
                });

            modelBuilder.Entity("EduDirectory3.Models.Calificacion", b =>
                {
                    b.Property<int>("IdCalificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCalificacion"));

                    b.Property<decimal>("CalificacionActividadesExtracurriculares")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("CalificacionAmbienteEscolar")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("CalificacionInfraestructura")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("CalificacionMetodologia")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("CalificacionProfesores")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("CalificacionSeguridad")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("IdEvaluacion")
                        .HasColumnType("int");

                    b.HasKey("IdCalificacion")
                        .HasName("PK__Califica__40E4A751755F3CF2");

                    b.HasIndex("IdEvaluacion");

                    b.ToTable("Calificacion");
                });

            modelBuilder.Entity("EduDirectory3.Models.Chatbot", b =>
                {
                    b.Property<int>("IdChatbot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdChatbot"));

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("IdChatbot")
                        .HasName("PK__Chatbot__3C18B2DC3D3A8D2B");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Chatbot");
                });

            modelBuilder.Entity("EduDirectory3.Models.Coordenada", b =>
                {
                    b.Property<int>("IdCoordenada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCoordenada"));

                    b.Property<decimal>("CoordenadaX")
                        .HasColumnType("decimal(18, 10)");

                    b.Property<decimal>("CoordenadaY")
                        .HasColumnType("decimal(18, 10)");

                    b.Property<int>("IdUbicacion")
                        .HasColumnType("int");

                    b.HasKey("IdCoordenada")
                        .HasName("PK__Coordena__6A279A16F8171065");

                    b.HasIndex("IdUbicacion");

                    b.ToTable("Coordenada");
                });

            modelBuilder.Entity("EduDirectory3.Models.Email", b =>
                {
                    b.Property<int>("IdEmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmail"));

                    b.Property<string>("Email1")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Email");

                    b.Property<int>("IdInstitucion")
                        .HasColumnType("int");

                    b.Property<string>("PerteneceA")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdEmail")
                        .HasName("PK__Email__E80F8BD4AD379777");

                    b.HasIndex("IdInstitucion");

                    b.ToTable("Email");
                });

            modelBuilder.Entity("EduDirectory3.Models.Evaluacion", b =>
                {
                    b.Property<int>("IdEvaluacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEvaluacion"));

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IdSede")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("MotivoReporte")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool?>("Reportado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("IdEvaluacion")
                        .HasName("PK__Evaluaci__A7EA657C6F2E62AE");

                    b.HasIndex("IdSede");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Evaluacion");
                });

            modelBuilder.Entity("EduDirectory3.Models.Filtro", b =>
                {
                    b.Property<int>("IdFiltro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFiltro"));

                    b.Property<int>("IdChatbot")
                        .HasColumnType("int");

                    b.Property<string>("NombreFiltro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdFiltro")
                        .HasName("PK__Filtro__0772E7B25D49E454");

                    b.HasIndex("IdChatbot");

                    b.ToTable("Filtro");
                });

            modelBuilder.Entity("EduDirectory3.Models.FormularioContacto", b =>
                {
                    b.Property<int>("IdFormularioContacto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFormularioContacto"));

                    b.Property<int>("IdSede")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdFormularioContacto")
                        .HasName("PK__Formular__EBDCB066ECFFFD80");

                    b.HasIndex("IdSede");

                    b.HasIndex("IdUsuario");

                    b.ToTable("FormularioContacto");
                });

            modelBuilder.Entity("EduDirectory3.Models.FormularioPreferencia", b =>
                {
                    b.Property<int>("IdFormularioPreferencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFormularioPreferencia"));

                    b.Property<int>("EdadEstudiante")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("MetodologiaPreferencia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Presupuesto")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TipoPreferencia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdFormularioPreferencia")
                        .HasName("PK__Formular__8AB0744AE928721C");

                    b.HasIndex("IdUsuario");

                    b.ToTable("FormularioPreferencia");
                });

            modelBuilder.Entity("EduDirectory3.Models.Institucion", b =>
                {
                    b.Property<int>("IdInstitucion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInstitucion"));

                    b.Property<string>("Calendario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("HorarioAtencion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Metodologia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PaginaWeb")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdInstitucion")
                        .HasName("PK__Instituc__4231815ADADD810D");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Institucion");
                });

            modelBuilder.Entity("EduDirectory3.Models.Jornada", b =>
                {
                    b.Property<int>("IdJornada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdJornada"));

                    b.Property<int>("IdSede")
                        .HasColumnType("int");

                    b.Property<string>("NombreJornada")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdJornada")
                        .HasName("PK__Jornada__FED2FEE8F46E0BC4");

                    b.HasIndex("IdSede");

                    b.ToTable("Jornada");
                });

            modelBuilder.Entity("EduDirectory3.Models.JornadaPreferencia", b =>
                {
                    b.Property<int>("IdJornadaPreferencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdJornadaPreferencia"));

                    b.Property<int>("IdFormularioPreferencia")
                        .HasColumnType("int");

                    b.Property<string>("NombreJornadaPreferencia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdJornadaPreferencia")
                        .HasName("PK__JornadaP__DF65943EB2F31AE7");

                    b.HasIndex("IdFormularioPreferencia");

                    b.ToTable("JornadaPreferencia");
                });

            modelBuilder.Entity("EduDirectory3.Models.Nivel", b =>
                {
                    b.Property<int>("IdNivel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNivel"));

                    b.Property<int>("IdSede")
                        .HasColumnType("int");

                    b.Property<string>("NombreNivel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdNivel")
                        .HasName("PK__Nivel__A7F93DEC5CEB3004");

                    b.HasIndex("IdSede");

                    b.ToTable("Nivel");
                });

            modelBuilder.Entity("EduDirectory3.Models.NivelPreferencia", b =>
                {
                    b.Property<int>("IdNivel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNivel"));

                    b.Property<int>("IdFormularioPreferencia")
                        .HasColumnType("int");

                    b.Property<string>("NombreNivelPreferencia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdNivel")
                        .HasName("PK__NivelPre__A7F93DECFB8771B2");

                    b.HasIndex("IdFormularioPreferencia");

                    b.ToTable("NivelPreferencia");
                });

            modelBuilder.Entity("EduDirectory3.Models.Rector", b =>
                {
                    b.Property<int>("IdRector")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRector"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("IdInstitucion")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdRector")
                        .HasName("PK__Rector__2BC2872E6C5BA223");

                    b.HasIndex("IdInstitucion");

                    b.ToTable("Rector");
                });

            modelBuilder.Entity("EduDirectory3.Models.ResultadosIcfes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<int>("IdInstitucion")
                        .HasColumnType("int");

                    b.Property<decimal>("Puntaje")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Resultad__3214EC079F84B606");

                    b.HasIndex("IdInstitucion");

                    b.ToTable("ResultadosIcfes");
                });

            modelBuilder.Entity("EduDirectory3.Models.Sede", b =>
                {
                    b.Property<int>("IdSede")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSede"));

                    b.Property<int>("IdInstitucion")
                        .HasColumnType("int");

                    b.Property<string>("NombreSede")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdSede")
                        .HasName("PK__Sede__A7780DFF6824DC6D");

                    b.HasIndex("IdInstitucion");

                    b.ToTable("Sede");
                });

            modelBuilder.Entity("EduDirectory3.Models.Servicio", b =>
                {
                    b.Property<int>("IdServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdServicio"));

                    b.Property<int>("IdSede")
                        .HasColumnType("int");

                    b.Property<string>("NombreServicio")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdServicio")
                        .HasName("PK__Servicio__2DCCF9A2B507655D");

                    b.HasIndex("IdSede");

                    b.ToTable("Servicio");
                });

            modelBuilder.Entity("EduDirectory3.Models.ServiciosPreferencia", b =>
                {
                    b.Property<int>("IdServicios")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdServicios"));

                    b.Property<int>("IdFormularioPreferencia")
                        .HasColumnType("int");

                    b.Property<string>("NombreServiciosPreferencia")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdServicios")
                        .HasName("PK__Servicio__011372997EF7B8B9");

                    b.HasIndex("IdFormularioPreferencia");

                    b.ToTable("ServiciosPreferencia");
                });

            modelBuilder.Entity("EduDirectory3.Models.Telefono", b =>
                {
                    b.Property<int>("IdTelefono")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTelefono"));

                    b.Property<int>("IdSede")
                        .HasColumnType("int");

                    b.Property<string>("NumeroTelefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdTelefono")
                        .HasName("PK__Telefono__9B8AC75331B9CB57");

                    b.HasIndex("IdSede");

                    b.ToTable("Telefono");
                });

            modelBuilder.Entity("EduDirectory3.Models.Ubicacion", b =>
                {
                    b.Property<int>("IdUbicacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUbicacion"));

                    b.Property<string>("Barrio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Comuna")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("IdSede")
                        .HasColumnType("int");

                    b.HasKey("IdUbicacion")
                        .HasName("PK__Ubicacio__778CAB1DE79913DD");

                    b.HasIndex("IdSede");

                    b.ToTable("Ubicacion");
                });

            modelBuilder.Entity("EduDirectory3.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdUsuario")
                        .HasName("PK__Usuario__5B65BF97754479C4");

                    b.HasIndex(new[] { "Correo" }, "UQ__Usuario__60695A1997325780")
                        .IsUnique();

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EduDirectory3.Models.ActividadExtracurricularPreferencia", b =>
                {
                    b.HasOne("EduDirectory3.Models.FormularioPreferencia", "IdFormularioPreferenciaNavigation")
                        .WithMany("ActividadExtracurricularPreferencia")
                        .HasForeignKey("IdFormularioPreferencia")
                        .IsRequired()
                        .HasConstraintName("FK_ActividadExtracurricularPreferencia_FormularioPreferencia");

                    b.Navigation("IdFormularioPreferenciaNavigation");
                });

            modelBuilder.Entity("EduDirectory3.Models.ActividadesExtracurriculares", b =>
                {
                    b.HasOne("EduDirectory3.Models.Sede", "IdSedeNavigation")
                        .WithMany("ActividadesExtracurriculares")
                        .HasForeignKey("IdSede")
                        .IsRequired()
                        .HasConstraintName("FK_ActividadesExtracurriculares_Sede");

                    b.Navigation("IdSedeNavigation");
                });

            modelBuilder.Entity("EduDirectory3.Models.Calificacion", b =>
                {
                    b.HasOne("EduDirectory3.Models.Evaluacion", "IdEvaluacionNavigation")
                        .WithMany("Calificacion")
                        .HasForeignKey("IdEvaluacion")
                        .IsRequired()
                        .HasConstraintName("FK_Calificacion_Evaluacion");

                    b.Navigation("IdEvaluacionNavigation");
                });

            modelBuilder.Entity("EduDirectory3.Models.Chatbot", b =>
                {
                    b.HasOne("EduDirectory3.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Chatbot")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_Chatbot_Usuario");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("EduDirectory3.Models.Coordenada", b =>
                {
                    b.HasOne("EduDirectory3.Models.Ubicacion", "IdUbicacionNavigation")
                        .WithMany("Coordenada")
                        .HasForeignKey("IdUbicacion")
                        .IsRequired()
                        .HasConstraintName("FK_Coordenada_Ubicacion");

                    b.Navigation("IdUbicacionNavigation");
                });

            modelBuilder.Entity("EduDirectory3.Models.Email", b =>
                {
                    b.HasOne("EduDirectory3.Models.Institucion", "IdInstitucionNavigation")
                        .WithMany("Email")
                        .HasForeignKey("IdInstitucion")
                        .IsRequired()
                        .HasConstraintName("FK_Email_Institucion");

                    b.Navigation("IdInstitucionNavigation");
                });

            modelBuilder.Entity("EduDirectory3.Models.Evaluacion", b =>
                {
                    b.HasOne("EduDirectory3.Models.Sede", "IdSedeNavigation")
                        .WithMany("Evaluacion")
                        .HasForeignKey("IdSede")
                        .IsRequired()
                        .HasConstraintName("FK_Evaluacion_Sede");

                    b.HasOne("EduDirectory3.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Evaluacion")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_Evaluacion_Usuario");

                    b.Navigation("IdSedeNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("EduDirectory3.Models.Filtro", b =>
                {
                    b.HasOne("EduDirectory3.Models.Chatbot", "IdChatbotNavigation")
                        .WithMany("Filtro")
                        .HasForeignKey("IdChatbot")
                        .IsRequired()
                        .HasConstraintName("FK_Filtro_Chatbot");

                    b.Navigation("IdChatbotNavigation");
                });

            modelBuilder.Entity("EduDirectory3.Models.FormularioContacto", b =>
                {
                    b.HasOne("EduDirectory3.Models.Sede", "IdSedeNavigation")
                        .WithMany("FormularioContacto")
                        .HasForeignKey("IdSede")
                        .IsRequired()
                        .HasConstraintName("FK_FormularioContacto_Sede");

                    b.HasOne("EduDirectory3.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("FormularioContacto")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_FormularioContacto_Usuario");

                    b.Navigation("IdSedeNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("EduDirectory3.Models.FormularioPreferencia", b =>
                {
                    b.HasOne("EduDirectory3.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("FormularioPreferencia")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_FormularioPreferencia_Usuario");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("EduDirectory3.Models.Institucion", b =>
                {
                    b.HasOne("EduDirectory3.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Institucion")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("FK_Institucion_Usuario");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("EduDirectory3.Models.Jornada", b =>
                {
                    b.HasOne("EduDirectory3.Models.Sede", "IdSedeNavigation")
                        .WithMany("Jornada")
                        .HasForeignKey("IdSede")
                        .IsRequired()
                        .HasConstraintName("FK_Jornada_Sede");

                    b.Navigation("IdSedeNavigation");
                });

            modelBuilder.Entity("EduDirectory3.Models.JornadaPreferencia", b =>
                {
                    b.HasOne("EduDirectory3.Models.FormularioPreferencia", "IdFormularioPreferenciaNavigation")
                        .WithMany("JornadaPreferencia")
                        .HasForeignKey("IdFormularioPreferencia")
                        .IsRequired()
                        .HasConstraintName("FK_JornadaPreferencia_FormularioPreferencia");

                    b.Navigation("IdFormularioPreferenciaNavigation");
                });

            modelBuilder.Entity("EduDirectory3.Models.Nivel", b =>
                {
                    b.HasOne("EduDirectory3.Models.Sede", "IdSedeNavigation")
                        .WithMany("Nivel")
                        .HasForeignKey("IdSede")
                        .IsRequired()
                        .HasConstraintName("FK_Nivel_Sede");

                    b.Navigation("IdSedeNavigation");
                });

            modelBuilder.Entity("EduDirectory3.Models.NivelPreferencia", b =>
                {
                    b.HasOne("EduDirectory3.Models.FormularioPreferencia", "IdFormularioPreferenciaNavigation")
                        .WithMany("NivelPreferencia")
                        .HasForeignKey("IdFormularioPreferencia")
                        .IsRequired()
                        .HasConstraintName("FK_NivelPreferencia_FormularioPreferencia");

                    b.Navigation("IdFormularioPreferenciaNavigation");
                });

            modelBuilder.Entity("EduDirectory3.Models.Rector", b =>
                {
                    b.HasOne("EduDirectory3.Models.Institucion", "IdInstitucionNavigation")
                        .WithMany("Rector")
                        .HasForeignKey("IdInstitucion")
                        .IsRequired()
                        .HasConstraintName("FK_Rector_Institucion");

                    b.Navigation("IdInstitucionNavigation");
                });

            modelBuilder.Entity("EduDirectory3.Models.ResultadosIcfes", b =>
                {
                    b.HasOne("EduDirectory3.Models.Institucion", "IdInstitucionNavigation")
                        .WithMany("ResultadosIcfes")
                        .HasForeignKey("IdInstitucion")
                        .IsRequired()
                        .HasConstraintName("FK_ResultadosIcfes_Institucion");

                    b.Navigation("IdInstitucionNavigation");
                });

            modelBuilder.Entity("EduDirectory3.Models.Sede", b =>
                {
                    b.HasOne("EduDirectory3.Models.Institucion", "IdInstitucionNavigation")
                        .WithMany("Sede")
                        .HasForeignKey("IdInstitucion")
                        .IsRequired()
                        .HasConstraintName("FK_Sede_Institucion");

                    b.Navigation("IdInstitucionNavigation");
                });

            modelBuilder.Entity("EduDirectory3.Models.Servicio", b =>
                {
                    b.HasOne("EduDirectory3.Models.Sede", "IdSedeNavigation")
                        .WithMany("Servicio")
                        .HasForeignKey("IdSede")
                        .IsRequired()
                        .HasConstraintName("FK_Servicio_Sede");

                    b.Navigation("IdSedeNavigation");
                });

            modelBuilder.Entity("EduDirectory3.Models.ServiciosPreferencia", b =>
                {
                    b.HasOne("EduDirectory3.Models.FormularioPreferencia", "IdFormularioPreferenciaNavigation")
                        .WithMany("ServiciosPreferencia")
                        .HasForeignKey("IdFormularioPreferencia")
                        .IsRequired()
                        .HasConstraintName("FK_ServiciosPreferencia_FormularioPreferencia");

                    b.Navigation("IdFormularioPreferenciaNavigation");
                });

            modelBuilder.Entity("EduDirectory3.Models.Telefono", b =>
                {
                    b.HasOne("EduDirectory3.Models.Sede", "IdSedeNavigation")
                        .WithMany("Telefono")
                        .HasForeignKey("IdSede")
                        .IsRequired()
                        .HasConstraintName("FK_Telefono_Sede");

                    b.Navigation("IdSedeNavigation");
                });

            modelBuilder.Entity("EduDirectory3.Models.Ubicacion", b =>
                {
                    b.HasOne("EduDirectory3.Models.Sede", "IdSedeNavigation")
                        .WithMany("Ubicacion")
                        .HasForeignKey("IdSede")
                        .IsRequired()
                        .HasConstraintName("FK_Ubicacion_Sede");

                    b.Navigation("IdSedeNavigation");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("EduDirectory3.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("EduDirectory3.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduDirectory3.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("EduDirectory3.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EduDirectory3.Models.Chatbot", b =>
                {
                    b.Navigation("Filtro");
                });

            modelBuilder.Entity("EduDirectory3.Models.Evaluacion", b =>
                {
                    b.Navigation("Calificacion");
                });

            modelBuilder.Entity("EduDirectory3.Models.FormularioPreferencia", b =>
                {
                    b.Navigation("ActividadExtracurricularPreferencia");

                    b.Navigation("JornadaPreferencia");

                    b.Navigation("NivelPreferencia");

                    b.Navigation("ServiciosPreferencia");
                });

            modelBuilder.Entity("EduDirectory3.Models.Institucion", b =>
                {
                    b.Navigation("Email");

                    b.Navigation("Rector");

                    b.Navigation("ResultadosIcfes");

                    b.Navigation("Sede");
                });

            modelBuilder.Entity("EduDirectory3.Models.Sede", b =>
                {
                    b.Navigation("ActividadesExtracurriculares");

                    b.Navigation("Evaluacion");

                    b.Navigation("FormularioContacto");

                    b.Navigation("Jornada");

                    b.Navigation("Nivel");

                    b.Navigation("Servicio");

                    b.Navigation("Telefono");

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("EduDirectory3.Models.Ubicacion", b =>
                {
                    b.Navigation("Coordenada");
                });

            modelBuilder.Entity("EduDirectory3.Models.Usuario", b =>
                {
                    b.Navigation("Chatbot");

                    b.Navigation("Evaluacion");

                    b.Navigation("FormularioContacto");

                    b.Navigation("FormularioPreferencia");

                    b.Navigation("Institucion");
                });
#pragma warning restore 612, 618
        }
    }
}
